create table measurement
(
    id          bigint generated by default as identity (start with 1),
    create_date timestamp      not null,
    qty         numeric(19, 2) not null,
    type        varchar(1)     not null,
    user_id     bigint         not null,
    primary key (id)
);

create table users
(
    id   bigint generated by default as identity (start with 1),
    name varchar(255) not null,
    primary key (id)
);

create index user_idx on measurement(user_id);
create index create_date_idx on measurement(create_date);

alter table measurement
    add constraint measurement_user_fk foreign key (user_id) references users;